version: "3.10.0"  # Specify the version of Docker Compose

services:
  fastapi:
    build: .
    container_name: fastapi-web-service
    ports:
      - "8000:8000"  # Map port 8000 of the container to port 8000 on your host
    restart: always  # Always restart the container if it fails
    environment:
      - ENV=development  # Optional environment variable if needed
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge  # Use the bridge network driver
